export const siteCopy = {
  brand: { zh: '谛深', en: 'Dishen' },
  current: { zh: '当前诗境', en: 'Exhibition' },
  archive: { zh: '作品档案', en: 'Archive' },
  about: { zh: '关于谛深', en: 'About' },
  credits: { zh: '素材署名', en: 'Credits' },
  theme: { zh: '切换明暗', en: 'Toggle theme' },
  language: { zh: 'English', en: '中文' },
  original: { zh: '原文', en: 'Original' },
  simplified: { zh: '简体', en: 'Simplified' },
  traditional: { zh: '繁体', en: 'Traditional' },
  pending: { zh: '文字已校 · 诗境待成', en: 'Text verified · Curation in progress' },
  enter: { zh: '入卷', en: 'Enter the scroll' },
  read: { zh: '静观此诗', en: 'Read this poem' },
  next: { zh: '下一境', en: 'Next poem' },
  previous: { zh: '上一境', en: 'Previous poem' },
  share: { zh: '分享此诗', en: 'Share' },
  copied: { zh: '链接已复制', en: 'Link copied' },
  skip: { zh: '跳至诗文', en: 'Skip to poem' },
} as const;
